http:
  port: 80
https:
  port: 443
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api1:
    host: '*'
    paths: '/service1/*'
  api2:
    host: '*'
    paths: '/producer/*'
serviceEndpoints:
  service1:
    url: 'http://service1:8001'
  producer:
    url: 'http://producer:8002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  service1:
    apiEndpoints:
      - api1
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: service1
              changeOrigin: true
  service2:
    apiEndpoints:
      - api2
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: producer
              changeOrigin: true