http:
  port: 80
# https:
#   port: 443
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api1:
    host: '*'
    paths: '/consumer*'
  api2:
    host: '*'
    paths: '/producer*'
  api3:
    host: '*'
    paths:
      - '/products*'
      - '/stores*'
      - '/product-categories*'
  api4:
    host: '*'
    paths: '/auth*'
  adminAPI:
    host: 'localhost'
    paths: '/admin*'
serviceEndpoints:
  consumer:
    url: 'http://consumer:8001'
  producer:
    url: 'http://producer:8002'
  products:
    url: 'http://products:8003'
  auth:
    url: 'http://auth:8004'
  adminBackend:
    url: 'http://localhost:9876'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  consumer:
    apiEndpoints:
      - api1
    policies:
      - oauth2:
      - proxy:
          - action:
              serviceEndpoint: consumer
              changeOrigin: true
  products:
    apiEndpoints:
      - api3
    policies:
      - proxy:
          - action:
              serviceEndpoint: products
              changeOrigin: true
  producer:
    apiEndpoints:
      - api2
    policies:
      - proxy:
          - action:
              serviceEndpoint: producer
              changeOrigin: true
  auth:
    apiEndpoints:
      - api4
    policies:
      - proxy:
          - action:
              serviceEndpoint: auth
              changeOrigin: true
  admin:
    apiEndpoints:
      - adminAPI
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminBackend
              stripPath: true
