services:

  db-products:
    image: 'postgres:latest'
    container_name: db-products
    environment:
      - POSTGRES_USER=dwallegro-products
      - POSTGRES_PASSWORD=dwallegro-products

  db-users:
    image: 'postgres:latest'
    container_name: db-users
    environment:
      - POSTGRES_USER=dwallegro-users
      - POSTGRES_PASSWORD=dwallegro-users

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  consumer:
    build: ./services/consumer
    image: kerdamon/consumer
    depends_on:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker

  producer:
    build: ./services/producer
    image: kerdamon/producer
    depends_on:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker

  products:
    build: ./services/products
    image: kerdamon/products
    depends_on:
      - db-products
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-products:5432/dwallegro-products
      - SPRING_DATASOURCE_USERNAME=dwallegro-products
      - SPRING_DATASOURCE_PASSWORD=dwallegro-products
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  auth:
    build: ./services/auth
    image: kerdamon/auth
    depends_on:
      - db-users
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/dwallegro-users
      - SPRING_DATASOURCE_USERNAME=dwallegro-users
      - SPRING_DATASOURCE_PASSWORD=dwallegro-users
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  api-gateway:
    build:
      context: ./api-gateway
    image: kerdamon/api-gateway
    ports:
      # - "443:443"
      - "80:80"
    depends_on:
      - consumer
      - producer
      - products
      - auth
