services:
  service1:
    build: ./services/service1
    image: kerdamon/service1
  producer-service:
    build: ./services/producer-service
    image: kerdamon/producer-service
    ports:
      - "8082:8082"
  api-gateway:
    build:
      context: ./api-gateway
    image: kerdamon/api-gateway
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - service1
      - producer-service
