services:
  service1:
    build: ./services/service1
    image: kerdamon/service1
  producer:
    build: ./services/producer
    image: kerdamon/producer
  api-gateway:
    build:
      context: ./api-gateway
    image: kerdamon/api-gateway
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - service1
      - producer
