name: 'Save build'
description: 'Save build folder of specified service'

inputs:
  name:
    description: 'Name of the service'
    required: true

runs:
  using: "composite"
  steps:
    - run: ls
      shell: bash
    - run: ls services
      shell: bash
    - run: ls services/service1
      shell: bash
    - run: ls services/service1/build
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: build-folder-${{ inputs.name }}
        path: services/${{ inputs.name }}/build
