name: 'Load build'
description: 'Load all build folders, and place them into proper folder of service'

runs:
  using: "composite"
  steps:
    - name: Load build folder of producer service
      uses: actions/download-artifact@v3
      with:
        name: build-folder-producer
        path: services/producer/build

    - name: Load build folder of products service
      uses: actions/download-artifact@v3
      with:
        name: build-folder-products
        path: services/products/build

    - name: Load build folder of mailer service
      uses: actions/download-artifact@v3
      with:
        name: build-folder-products
        path: services/mailer/build
