name: 'Build services'
description: 'Build Services with Gradle'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: service1

    - name: Cache build folder # to use in other jobs
      uses: actions/cache@v3
      with:
        path: service1/build
        key: ${{ runner.os }}-build-${{ hashFiles('**/service1.jar') }}
