name: 'Build service'
description: 'Build Service with Gradle'

inputs:
  name:
    description: 'Path to the service, that corresponds to its name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Load build folder
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}-build-folder

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
        build-root-directory: ${{ inputs.name }}

    - run: mkdir -p artifact_temp/services/${{ inputs.name }}/ && cp -p artifact_temp/services/${{ inputs.name }}/build/ artifact_temp/services/${{ inputs.name }}/build/
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}-build-folder
        path: artifact_temp


