name: Build images and push to production

on:
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Services: [service1]
    steps:
      - uses: actions/checkout@v3
      - name: Build Service ${{ matrix.Services }}
        uses: ./.github/actions/build-services
        with: 
          name: ${{ matrix.Services }}

  build-images-and-push:
    runs-on: ubuntu-latest
    needs: build-services
    steps:
      - uses: actions/checkout@v3
      - name: Load build folder
        uses: actions/download-artifact@v3
        with:
          name: service1-build-folder
          path: service1/build
      - run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker compose build
      - run: docker compose push
