name: Build images and push to production

on:
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-services
      - run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker compose build
      - run: docker compose push
