name: Build and test project with Gradle and Docker

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Services: [consumer, producer]
    steps:
      - uses: actions/checkout@v3
      - name: Build Service ${{ matrix.Services }}
        uses: ./.github/actions/build-service
        with: 
          name: ${{ matrix.Services }}

  test-services:
    runs-on: ubuntu-latest
    needs: build-services
    strategy:
      matrix:
        Services: [consumer, producer]
    steps:
      - uses: actions/checkout@v3
      - name: Test Service ${{ matrix.Services }}
        uses: ./.github/actions/test-service
        with: 
          name: ${{ matrix.Services }}

  snyk-gradle:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    needs: test-services
    strategy:
      matrix:
        Services: [consumer, producer]
    steps:
      - uses: actions/checkout@v3

      - name: Check Service ${{ matrix.Services }} for vulnerabilities with Snyk
        uses: ./.github/actions/snyk-check-service
        with: 
          name: ${{ matrix.Services }}
          token: ${{ secrets.SNYK_TOKEN_KERDAMON }}

  build-images:
    runs-on: ubuntu-latest
    needs: [ build-services, test-services ]
    steps:
      - uses: actions/checkout@v3
      - name: Load build folders
        uses: ./.github/actions/load-builds
      - run: docker compose build
      - run: docker compose up -d
