name: Java CI with Gradle

on:
  push:
    branches: [ "master", "add-github-actions" ]
  pull_request:
    branches: [ "master", "add-github-actions" ]

permissions:
  contents: read

jobs:

  build-service1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change permissions for file
      run: chmod +x service1/gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: service1

  compose-up:

    runs-on: ubuntu-latest

    needs: build-service1

    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: ls
    - name: Docker compose up
      run: docker compose build
