name: Build and test project with Gradle and Docker

on:
  push:
    branches: '**'

permissions:
  contents: read

jobs:
  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Services: [service1]
    steps:
      - uses: actions/checkout@v3
      - name: Build Service ${{ matrix.Services }}
        uses: ./.github/actions/build-service
        with: 
          name: ${{ matrix.Services }}

  build-images:
    runs-on: ubuntu-latest
    needs: build-services
    steps:
      - uses: actions/checkout@v3
      - name: Load build folder
        uses: actions/download-artifact@v3
        with:
          name: service-build-folder*
      - run: docker compose build
      - run: docker compose up -d
